version: "3"
services:
    web:
        build: .
        ports:
            - "3500"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "toTO123456!&@"
            ACCEPT_EULA: "Y"