version: "3"
services:
    web:
        build: .
        ports:
            - "44375"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "toto123456"
            ACCEPT_EULA: "Y"